/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.33.0
 * Product:       sht3x
 * Model-Version: 1.0.0
 */
/*
 * Copyright (c) 2023, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sht3x_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

static uint8_t communication_buffer[6] = {0};

static uint8_t _i2c_address;

void sht3x_init(uint8_t i2c_address) {
    _i2c_address = i2c_address;
}

float signal_temperature(uint16_t temperature_ticks) {
    float temperature = 0.0;
    temperature = (float)(temperature_ticks);
    temperature = -45 + ((temperature * 175.0) / 65535.0);
    return temperature;
}

float signal_humidity(uint16_t humidity_ticks) {
    float humidity = 0.0;
    humidity = (float)(humidity_ticks);
    humidity = (100 * humidity) / 65535.0;
    return humidity;
}

int16_t sht3x_measure_single_shot(repeatability measurement_repeatability,
                                  bool is_clock_stretching,
                                  float* a_temperature, float* a_humidity) {
    uint16_t raw_temp = 0;
    uint16_t raw_humi = 0;
    int16_t local_error = 0;
    if (is_clock_stretching) {
        if (measurement_repeatability == REPEATABILITY_HIGH) {
            local_error =
                sht3x_measure_single_shot_high_repeatability_clock_stretching(
                    &raw_temp, &raw_humi);
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
            local_error =
                sht3x_measure_single_shot_medium_repeatability_clock_stretching(
                    &raw_temp, &raw_humi);
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_LOW) {
            local_error =
                sht3x_measure_single_shot_low_repeatability_clock_stretching(
                    &raw_temp, &raw_humi);
            if (local_error != NO_ERROR) {
                return local_error;
            }
        }
    } else if (measurement_repeatability == REPEATABILITY_HIGH) {
        local_error =
            sht3x_measure_single_shot_high_repeatability(&raw_temp, &raw_humi);
        if (local_error != NO_ERROR) {
            return local_error;
        }
    } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
        local_error = sht3x_measure_single_shot_medium_repeatability(&raw_temp,
                                                                     &raw_humi);
        if (local_error != NO_ERROR) {
            return local_error;
        }
    } else if (measurement_repeatability == REPEATABILITY_LOW) {
        local_error =
            sht3x_measure_single_shot_low_repeatability(&raw_temp, &raw_humi);
        if (local_error != NO_ERROR) {
            return local_error;
        }
    }
    *a_temperature = signal_temperature(raw_temp);
    *a_humidity = signal_humidity(raw_humi);
    return local_error;
}

int16_t
sht3x_start_periodic_measurement(repeatability measurement_repeatability,
                                 mps messages_per_second) {
    int16_t local_error = 0;
    if (messages_per_second == MPS_EVERY_TWO_SECONDS) {
        if (measurement_repeatability == REPEATABILITY_HIGH) {
            local_error = sht3x_start_measurement_0_5_mps_high_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
            local_error =
                sht3x_start_measurement_0_5_mps_medium_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_LOW) {
            local_error = sht3x_start_measurement_0_5_mps_low_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        }
    } else if (messages_per_second == MPS_ONE_PER_SECOND) {
        if (measurement_repeatability == REPEATABILITY_HIGH) {
            local_error = sht3x_start_measurement_1_mps_high_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
            local_error = sht3x_start_measurement_1_mps_medium_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_LOW) {
            local_error = sht3x_start_measurement_1_mps_low_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        }
    } else if (messages_per_second == MPS_TWO_PER_SECOND) {
        if (measurement_repeatability == REPEATABILITY_HIGH) {
            local_error = sht3x_start_measurement_2_mps_high_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
            local_error = sht3x_start_measurement_2_mps_medium_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_LOW) {
            local_error = sht3x_start_measurement_2_mps_low_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        }
    } else if (messages_per_second == MPS_FOUR_PER_SECOND) {
        if (measurement_repeatability == REPEATABILITY_HIGH) {
            local_error = sht3x_start_measurement_4_mps_high_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
            local_error = sht3x_start_measurement_4_mps_medium_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_LOW) {
            local_error = sht3x_start_measurement_4_mps_low_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        }
    } else if (messages_per_second == MPS_TEN_PER_SECOND) {
        if (measurement_repeatability == REPEATABILITY_HIGH) {
            local_error = sht3x_start_measurement_10_mps_high_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_MEDIUM) {
            local_error = sht3x_start_measurement_10_mps_medium_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        } else if (measurement_repeatability == REPEATABILITY_LOW) {
            local_error = sht3x_start_measurement_10_mps_low_repeatability();
            if (local_error != NO_ERROR) {
                return local_error;
            }
        }
    }
    return local_error;
}

int16_t sht3x_blocking_read_measurement(float* a_temperature,
                                        float* a_humidity) {
    uint16_t status = 0u;
    uint16_t data_ready_flag = 0u;
    uint16_t raw_temp = 0;
    uint16_t raw_humi = 0;
    int16_t local_error = 0;
    local_error = ll_sht3x_read_status_register(&status);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    data_ready_flag = (status >> 6) & 15;
    while (data_ready_flag == 0) {
        sensirion_hal_sleep_us(100000);
        local_error = ll_sht3x_read_status_register(&status);
        if (local_error != NO_ERROR) {
            return local_error;
        }
        data_ready_flag = (status >> 6) & 15;
    }
    local_error = sht3x_read_measurement(&raw_temp, &raw_humi);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *a_temperature = signal_temperature(raw_temp);
    *a_humidity = signal_humidity(raw_humi);
    return local_error;
}

int16_t sht3x_read_status_register(uint16_t* a_status_register) {
    uint16_t status = 0u;
    int16_t local_error = 0;
    local_error = ll_sht3x_read_status_register(&status);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *a_status_register = (uint16_t)(status);

    return local_error;
}

int16_t
sht3x_measure_single_shot_high_repeatability(uint16_t* temperature_ticks,
                                             uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2400);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t sht3x_measure_single_shot_high_repeatability_clock_stretching(
    uint16_t* temperature_ticks, uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2c06);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t
sht3x_measure_single_shot_medium_repeatability(uint16_t* temperature_ticks,
                                               uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x240b);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t sht3x_measure_single_shot_medium_repeatability_clock_stretching(
    uint16_t* temperature_ticks, uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2c0d);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t sht3x_measure_single_shot_low_repeatability(uint16_t* temperature_ticks,
                                                    uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2416);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t sht3x_measure_single_shot_low_repeatability_clock_stretching(
    uint16_t* temperature_ticks, uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2c10);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t sht3x_start_measurement_0_5_mps_high_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2032);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_0_5_mps_medium_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2024);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_0_5_mps_low_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x202f);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_1_mps_high_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2130);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_1_mps_medium_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2126);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_1_mps_low_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x212d);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_2_mps_high_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2236);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_2_mps_medium_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2220);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_2_mps_low_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x222b);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_4_mps_high_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2334);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_4_mps_medium_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2322);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_4_mps_low_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2329);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_10_mps_high_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2737);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(16 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_10_mps_medium_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2721);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(7 * 1000);
    return local_error;
}

int16_t sht3x_start_measurement_10_mps_low_repeatability() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x273a);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5 * 1000);
    return local_error;
}

int16_t sht3x_start_art_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2b32);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    return local_error;
}

int16_t sht3x_read_measurement(uint16_t* temperature_ticks,
                               uint16_t* humidity_ticks) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe000);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    return local_error;
}

int16_t sht3x_stop_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3093);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t sht3x_enable_heater() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x306d);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t sht3x_disable_heater() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3066);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t ll_sht3x_read_status_register(uint16_t* status_register) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xf32d);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *status_register = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sht3x_clear_status_register() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3041);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t sht3x_soft_reset() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x30a2);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(2 * 1000);
    return local_error;
}
